apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora03
  namespace: default
  labels:
    app: fedora03
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: fedora03
        namespace: default
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          volumeMode: Filesystem
        source:
          http:
            url: "https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.qcow2"
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora03
        special: fedora03
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - masquerade: {}
            name: default
          rng: {}
        resources:
          requests:
            memory: 1Gi
      evictionStrategy: LiveMigrate
      hostname: fedora03
      networks:
      - name: default
        pod: {}
      volumes:
        - dataVolume:
            name: fedora03
          name: rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True