apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora01
  namespace: default
  labels:
    app: fedora01
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: fedora01
        namespace: default
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          volumeMode: Filesystem
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora01
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - masquerade: {}
            name: default
          rng: {}
        resources:
          requests:
            memory: 1Gi
      evictionStrategy: LiveMigrate
      hostname: fedora01
      networks:
      - name: default
        pod: {}
      volumes:
        - dataVolume:
            name: fedora01
          name: rootdisk