apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora07
  namespace: default
  labels:
    app: fedora07
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: fedora07
        namespace: default
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          volumeMode: Filesystem
        source:
          pvc:
            name: fedora-registry
            namespace: default
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora07
        special: fedora07
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          - disk: {}
            name: app-config-disk
            serial: CVLY623300HK240D
          interfaces:
          - masquerade: {}
            name: default
          rng: {}
        resources:
          requests:
            memory: 1Gi
      evictionStrategy: LiveMigrate
      hostname: fedora07
      networks:
      - name: default
        pod: {}
      volumes:
        - dataVolume:
            name: fedora07
          name: rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True
              bootcmd:
              - "mkdir /mnt/extra-config"
              - "mount /dev/$(lsblk --nodeps -no name,serial | grep CVLY623300HK240D | cut -f1 -d' ') /mnt/extra-config"
        - configMap:
            name: kube-root-ca.crt
          name: app-config-disk