kind: VirtualMachineDeployment
deployment:
  name: ${NAME}
  namespace: ${NAMESPACE}
  vm: vm.yaml
  image:
    enabled: true
    ip: ${TOOLS_IP}
    username: ${TOOLS_USERNAME}
    password: "${TOOLS_PASSWORD}"
    path: ${IMAGE_PATH}${IMAGE_FILENAME}
    size: ${IMAGE_SIZE}
    dv: image.yaml
  day0:
    enabled: true
    filename: iosxe_config.txt
    source: iosxe_config.txt
    destination: c8000v_config.iso
    size: ${DAY0_SIZE}
    dv: day0.yaml
  multus:
    enabled: true
    network:
    - network.yaml
  service:
    ssh: ssh.yaml
variables:
  NAME: cat8kv-m-1
  NAMESPACE: default
  NODE: ocp-bm2
  CORES: 1
  SOCKETS: 1
  THREADS: 1
  MEMORY: 4Gi
  IMAGE_NAME: cat8kv-17.06.05-image
  IMAGE_NAMESPACE: default
  IMAGE_PATH: /home/cisco/image/
  IMAGE_FILENAME: c8000v-universalk9_8G_vga.17.06.05.qcow2
  IMAGE_SIZE: 10Gi
  DAY0_SIZE: 1Gi
  MACVLAN_MASTER: eno5
  NET1_VM_IP: 192.168.10.20
  NET1_BRIDGE_IP: 192.168.10.10
  NET1_NETMASK: 255.255.255.0
  NET1_PREFIX: 24
  SSH_USERNAME: admin
  SSH_PASSWORD: Cisco_123
  DOMAIN_NAME: cisco.com
  TOOLS_IP: 10.58.28.207
  TOOLS_USERNAME: cisco
  TOOLS_PASSWORD: "!Cisc0_123"
tools:
  enabled: true
  ip: ${TOOLS_IP}
  username: ${TOOLS_USERNAME}
  password: "${TOOLS_PASSWORD}"
ssh:
  enabled: true
  type: cisco
  username: ${SSH_USERNAME}
  password: ${SSH_PASSWORD}
ready:
  enabled: true
  type: ssh
  timeout: 600
  sleep: 120