authoritative;
ddns-update-style interim;
allow booting;
allow bootp;
allow unknown-clients;
ignore client-updates;
default-lease-time 14400;
max-lease-time 14400;

subnet ${INTERFACE_0_NETWORK} netmask ${INTERFACE_0_NETMASK} {
    range                           ${OCP_NODES_DHCP_START} ${OCP_NODES_DHCP_END};
    option routers                  ${INTERFACE_0_GATEWAY};
    option subnet-mask              ${INTERFACE_0_NETMASK};
    option domain-name              "${OCP_BASE_DOMAIN}";
    option domain-name-servers      ${INTERFACE_0_IP};
    option ntp-servers              ${NTP_SERVER};
}
