apiVersion: v1
kind: Service
metadata:
  name: cat8kv-01-netconf
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 830
    protocol: TCP
    targetPort: 830
  selector:
    special: cat8kv-01
  type: NodePort