linux:
  template: centos
  ks:
    enabled: True
  iso:
    filename: CentOS-Stream-8-x86_64-20220915-dvd1.iso
  vm:
    name: centos-sample-tasks
    cpu: 1
    memory: 2048
    disk:
      size: 50
    interface:
      network: VM Network
      name: ens192
      type: vmxnet3
    ip: 10.58.29.76/28
    gateway: 10.58.29.78
    dns:
      servers: 144.254.71.184
      domain: cisco.com
    ntp:
      servers: 144.254.15.78
      timezone: Europe/Rome
    password: cisco