apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cat8kv-dv
spec:
  source:
      upload: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi