apiVersion: v1
kind: ConfigMap
metadata:
  name: twamp-insecure-config
  namespace: default
data:
  config.json: |
    {
      "agent_id": "Enterprise",
      "log_level": "WARNING",
      "probes": [
        {
          "id": "Insecure",
          "source": "0.0.0.0:20001",
          "destination": "172.70.66.67:20862",
          "cadence": 5,
          "options": {}
        }
      ],
      "reflector": {},
      "collectors": [{
        "type": "HTTP",
        "endpoint": "http://docker.emea-sp.cisco.com:8246/twamp/collector"
      }]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-twamp-insecure
spec:
  selector:
    matchLabels:
      app: my-twamp-insecure
  template:
    metadata:
      labels:
        app: my-twamp-insecure
    spec:
      volumes:
      - name: twamp-insecure-config-volume
        configMap:
          name: twamp-insecure-config
      containers:
      - name: agent
        image: containers.cisco.com/adt_emear/twamp-agent
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /app/config.json
          subPath: config.json
          name: twamp-insecure-config-volume