apiVersion: v1
kind: Service
metadata:
  name: ${NAME}-ssh
  namespace: ${NAMESPACE}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    special: ${NAME}
  type: NodePort