apiVersion: v1
baseDomain: ${OCP_BASE_DOMAIN}
proxy:
  httpProxy: ${HTTP_PROXY}
  httpsProxy: ${HTTPS_PROXY}
  noProxy: localhost,.${OCP_BASE_DOMAIN},${VCENTER_NAME},${VCENTER_IP},${VCENTER_CLUSTER_HOST_IPS},${INTERFACE_0_IP},${OCP_API_VIP},${OCP_INGRESS_VIP},${OCP_NODES_IPS}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: ${OCP_WORKER_COUNT}
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 8192
      osDisk:
        diskSizeGB: 120
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: ${OCP_MASTER_COUNT}
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
metadata:
  name: ${OCP_NAME}
platform:
  vsphere:
    vcenter: ${VCENTER_NAME}
    username: ${VCENTER_USERNAME}
    password: "${VCENTER_PASSWORD}"
    datacenter: ${VCENTER_DATACENTER}
    defaultDatastore: ${VCENTER_DATASTORE}
    folder: /${VCENTER_DATACENTER}/vm/${VCENTER_VM_FOLDER}
    diskType: thin
    network: ${INTERFACE_0_VC_NETWORK_NAME}
    cluster: ${VCENTER_CLUSTER}
    apiVIP: ${OCP_API_VIP}
    ingressVIP: ${OCP_INGRESS_VIP}
fips: false
pullSecret: 'PULL_SECRET_FILE'
sshKey: 'SSH_PUBLIC_KEY'