def get_supported_tasks():
    supported_tasks = [
        'ai',
        'cli', 
        'cli-web',
        'gpu', 
        'grafana',
        'prometheus',
        'identity', 
        'imm',
        'iotel',
        'lso',
        'lvm',
        'minio',
        'nfd', 
        'nfs',
        'nim',
        'nmstate', 
        'cnv',
        'mtv',
        'odf',
        'portworx',
        'serverless',
        'service-mesh',
        'sriov', 
        'ssh', 
        'splunk', 
        'tetragon',
        'trident',
        'cert-manager',
        'cilium-image',
        'cilium-bgp',
        'cilium-timescape',
        'cilium-mesh',
        'cilium-pnet',
        'cilium-inb'
    ]
    return supported_tasks
