apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: csr1kv-01-day0
  namespace: default
spec:
  source:
      upload: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeMode: Block