kind: VirtualMachineDeployment
deployment:
  vm: vm.yaml
  iso:
    source: iosxe_config.txt
    destination: csr_config.iso
    dv: day0.yaml
  service:
    ssh: svc.yaml
ready:
  enabled: true
  type: ssh
  username: admin
  password: Cisco_123
  timeout: 600
report:
  enabled: true